'use client'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'
import { Logo } from '@/components/Logo'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Skeleton } from '@/components/ui/skeleton'
import { Fish, Bookmark, BookmarkCheck, Trash2, Download, LogOut, Crown } from 'lucide-react'

export default function AccountPage() {
  const supabase = createClient()
  const router = useRouter()
  const [user, setUser] = useState<any>(null)
  const [profile, setProfile] = useState<any>(null)
  const [reports, setReports] = useState<any[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    async function load() {
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) { router.push('/auth/login?next=/account'); return }
      setUser(user)
      const [{ data: prof }, { data: reps }] = await Promise.all([
        supabase.from('profiles').select('*').eq('id', user.id).maybeSingle(),
        supabase.from('saved_reports').select('*').eq('user_id', user.id).order('pinned', { ascending: false }).order('created_at', { ascending: false })
      ])
      setProfile(prof)
      setReports(reps || [])
      setLoading(false)
    }
    load()
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const trialDaysLeft = profile?.trial_started_at
    ? Math.max(0, 7 - Math.floor((Date.now() - new Date(profile.trial_started_at).getTime()) / 86400000))
    : 7
  const isTrialExpired = profile?.subscription_status === 'trial' && trialDaysLeft === 0

  async function togglePin(id: string, pinned: boolean) {
    await supabase.from('saved_reports').update({ pinned: !pinned }).eq('id', id)
    setReports(rs => rs.map(r => r.id === id ? { ...r, pinned: !pinned } : r).sort((a, b) => {
      if (a.pinned && !b.pinned) return -1
      if (!a.pinned && b.pinned) return 1
      return new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
    }))
  }

  async function deleteReport(id: string) {
    if (!confirm('Remove this report from your history?')) return
    await supabase.from('saved_reports').delete().eq('id', id)
    setReports(rs => rs.filter(r => r.id !== id))
  }

  function exportPDF(report: any) {
    const win = window.open('', '_blank')
    if (!win) return
    const result = report.result_data || {}
    const summary = report.summary_data || {}
    const weather = report.weather_data || {}
    const topBaits = (result.topBaits || []).slice(0, 5).map((b: any) => `<li>${b.name} (${b.count}x)</li>`).join('')
    const topPatterns = (result.topPatterns || []).slice(0, 4).map((p: any) => `<li>${p.pattern} (${p.count}x)</li>`).join('')
    win.document.write(`<!DOCTYPE html><html><head><title>AnglerIQ Report — ${report.lake_name}</title>
<style>
  body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; color: #1e293b; font-size: 14px; line-height: 1.6; }
  h1 { font-size: 24px; font-weight: 900; margin-bottom: 4px; }
  h2 { font-size: 16px; font-weight: 700; margin-top: 24px; margin-bottom: 8px; color: #1d4ed8; border-bottom: 2px solid #e2e8f0; padding-bottom: 4px; }
  .meta { color: #64748b; font-size: 13px; margin-bottom: 16px; }
  .weather { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 12px 16px; margin-bottom: 16px; font-size: 13px; }
  ul { padding-left: 20px; margin: 0; }
  li { margin-bottom: 4px; }
  .intel { white-space: pre-wrap; }
  .footer { margin-top: 40px; font-size: 11px; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 16px; }
  @media print { body { margin: 20px; } }
</style></head><body>
<h1>🎣 ${report.lake_name}</h1>
<div class="meta">${result.water?.state || ''} · ${result.water?.type || ''} · ${report.trip_date ? 'Trip: ' + report.trip_date : 'Report date: ' + new Date(report.created_at).toLocaleDateString()} · ${result.sampleSize || 0} tournament reports</div>
${weather.tempF ? `<div class="weather">⛅ ${weather.tempF}°F · ${weather.skyCondition || ''} · ${weather.windMph || 0} mph wind · ${weather.season || ''}</div>` : ''}
<h2>Top Baits</h2><ul>${topBaits || '<li>No bait data</li>'}</ul>
<h2>Top Patterns</h2><ul>${topPatterns || '<li>No pattern data</li>'}</ul>
${summary.intel ? `<h2>Tournament Intel</h2><div class="intel">${summary.intel}</div>` : ''}
${summary.today ? `<h2>Recommendation</h2><div class="intel">${summary.today}</div>` : ''}
<div class="footer">Generated by AnglerIQ · getangleriq.com · ${new Date().toLocaleDateString()}</div>
</body></html>`)
    win.document.close()
    setTimeout(() => win.print(), 500)
  }

  async function handleSignOut() {
    await supabase.auth.signOut()
    router.push('/')
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-50" style={{ fontFamily: 'var(--font-montserrat), sans-serif' }}>
        <nav className="flex items-center justify-between px-6 py-4 border-b border-slate-100 bg-white">
          <Link href="/"><Logo className="h-7 w-auto" /></Link>
        </nav>
        <div className="max-w-3xl mx-auto px-4 py-8 space-y-4">
          <Skeleton className="h-24 w-full" />
          <Skeleton className="h-16 w-full" />
          <Skeleton className="h-32 w-full" />
        </div>
      </div>
    )
  }

  const displayName = profile?.full_name || user?.email?.split('@')[0] || 'Angler'
  const initials = displayName.split(' ').map((n: string) => n[0]).join('').toUpperCase().slice(0, 2)

  return (
    <div className="min-h-screen bg-slate-50" style={{ fontFamily: 'var(--font-montserrat), sans-serif' }}>
      <nav className="flex items-center justify-between px-6 py-4 border-b border-slate-100 bg-white sticky top-0 z-10">
        <Link href="/"><Logo className="h-7 w-auto" /></Link>
        <button onClick={handleSignOut} className="flex items-center gap-1.5 text-sm text-slate-500 hover:text-slate-700 font-semibold">
          <LogOut size={14} /> Sign Out
        </button>
      </nav>

      <div className="max-w-3xl mx-auto px-4 py-8 space-y-6">
        {/* Profile card */}
        <div className="bg-white border border-slate-200 rounded-xl p-6 flex items-center gap-5">
          <div className="w-16 h-16 rounded-full bg-blue-600 flex items-center justify-center text-white font-extrabold text-xl shrink-0">
            {initials}
          </div>
          <div className="flex-1 min-w-0">
            <h1 className="text-xl font-extrabold text-slate-900">{displayName}</h1>
            <p className="text-slate-500 text-sm">{user?.email}</p>
          </div>
          <Link href="/search">
            <Button className="bg-blue-600 hover:bg-blue-700 text-white font-bold text-sm">New Report</Button>
          </Link>
        </div>

        {/* Subscription status */}
        <div className="bg-white border border-slate-200 rounded-xl p-5">
          <div className="flex items-center justify-between flex-wrap gap-3">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <Crown size={16} className="text-amber-500" />
                <span className="font-bold text-slate-900 text-sm">Subscription</span>
                {profile?.subscription_status === 'trial' && !isTrialExpired && (
                  <Badge className="bg-green-50 text-green-700 border-green-200 text-xs font-semibold">Free Trial</Badge>
                )}
                {profile?.subscription_status === 'active' && (
                  <Badge className="bg-blue-50 text-blue-700 border-blue-200 text-xs font-semibold">Pro Active</Badge>
                )}
                {isTrialExpired && (
                  <Badge className="bg-red-50 text-red-700 border-red-200 text-xs font-semibold">Trial Expired</Badge>
                )}
                {!profile && (
                  <Badge className="bg-green-50 text-green-700 border-green-200 text-xs font-semibold">Free Trial</Badge>
                )}
              </div>
              {(profile?.subscription_status === 'trial' || !profile) && !isTrialExpired && (
                <p className="text-slate-500 text-sm">{trialDaysLeft} day{trialDaysLeft !== 1 ? 's' : ''} remaining in your free trial</p>
              )}
              {isTrialExpired && (
                <p className="text-slate-500 text-sm">Your trial has ended. Upgrade to continue accessing reports.</p>
              )}
              {profile?.subscription_status === 'active' && (
                <p className="text-slate-500 text-sm">Pro plan · Full access</p>
              )}
            </div>
            {profile?.subscription_status !== 'active' && (
              <Button
                onClick={() => alert('Payment coming soon! Your trial access continues for now.')}
                className="bg-amber-500 hover:bg-amber-600 text-white font-bold text-sm"
              >
                Upgrade to Pro — $9.99/mo
              </Button>
            )}
          </div>
        </div>

        {/* Report history */}
        <div>
          <div className="flex items-center justify-between mb-3">
            <h2 className="text-sm font-bold text-slate-500 uppercase tracking-wider flex items-center gap-2">
              <Fish size={14} /> Saved Reports ({reports.length})
            </h2>
          </div>

          {reports.length === 0 ? (
            <div className="bg-white border border-slate-200 rounded-xl p-10 text-center">
              <Fish size={36} className="mx-auto mb-3 text-slate-200" strokeWidth={1} />
              <p className="text-slate-500 font-semibold">No saved reports yet</p>
              <p className="text-slate-400 text-sm mt-1">Run a search and save your first report.</p>
              <Link href="/search" className="mt-4 inline-block">
                <Button className="bg-blue-600 hover:bg-blue-700 text-white font-bold text-sm mt-4">Run a Report</Button>
              </Link>
            </div>
          ) : (
            <div className="space-y-3">
              {reports.map(report => {
                const result = report.result_data || {}
                const topBaits = (result.topBaits || []).slice(0, 2)
                return (
                  <div key={report.id} className={`bg-white border rounded-xl p-4 flex flex-col sm:flex-row gap-4 ${report.pinned ? 'border-amber-300 bg-amber-50' : 'border-slate-200'}`}>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-start gap-2 flex-wrap">
                        {report.pinned && <span title="Pinned" className="text-amber-500">📌</span>}
                        <div>
                          <p className="font-bold text-slate-900">{report.lake_name}</p>
                          <p className="text-slate-400 text-xs">{report.lake_state} · {report.trip_date ? `Trip: ${report.trip_date}` : 'Right Now report'} · Saved {new Date(report.created_at).toLocaleDateString()}</p>
                        </div>
                      </div>
                      {topBaits.length > 0 && (
                        <div className="flex flex-wrap gap-1.5 mt-2">
                          {topBaits.map((b: any) => (
                            <Badge key={b.name} variant="outline" className="border-slate-200 text-slate-600 text-xs">{b.name}</Badge>
                          ))}
                        </div>
                      )}
                    </div>
                    <div className="flex items-center gap-2 shrink-0">
                      <button
                        onClick={() => togglePin(report.id, report.pinned)}
                        title={report.pinned ? 'Unpin' : 'Pin to top'}
                        className={`p-1.5 rounded-lg hover:bg-slate-100 transition-colors ${report.pinned ? 'text-amber-500' : 'text-slate-400'}`}
                      >
                        {report.pinned ? <BookmarkCheck size={16} /> : <Bookmark size={16} />}
                      </button>
                      <button
                        onClick={() => exportPDF(report)}
                        title="Export to PDF"
                        className="p-1.5 rounded-lg hover:bg-slate-100 text-slate-400 hover:text-blue-600 transition-colors"
                      >
                        <Download size={16} />
                      </button>
                      <button
                        onClick={() => deleteReport(report.id)}
                        title="Remove report"
                        className="p-1.5 rounded-lg hover:bg-red-50 text-slate-400 hover:text-red-500 transition-colors"
                      >
                        <Trash2 size={16} />
                      </button>
                    </div>
                  </div>
                )
              })}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
